Included an option to add harbor registry to registry-config
giantswarm/cluster-aws pull request #199
Opened 2023-01-11 11:29 UTC by DeeAjayi

Co-authored-by: William Young <will.young@engineerbetter.com>

### What this PR does / why we need it

### Checklist

- [ ] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test create
/test upgrade

2023-01-11 11:46 UTC, calvix commented
Changelog entry is missing

2023-01-11 12:17 UTC, AndiDog requested changes

2023-01-11 12:17 UTC, AndiDog commented on helm/cluster-aws/files/etc/containerd/conf.d/registry-config.toml
> +      endpoint = ["{{ .Values.harborRegistry.username }}"", "https://registry-1.docker.io", "giantswarm.azurecr.io"]
There's a double `"` which makes the config invalid.

Also, do we really need to copy all values in the _else_ branch, or could we put the 2-3 endpoints into multiple lines and only use an `if` clause for harbor?

2023-01-13 08:56 UTC, MarcelMue commented on helm/cluster-aws/files/etc/containerd/conf.d/registry-config.toml
> +        "{{ include fullurl }}"
```suggestion
        "{{ include fullurl . }}"
```

2023-01-13 09:13 UTC, DeeAjayi commented on helm/cluster-aws/files/etc/containerd/conf.d/registry-config.toml
> +        "{{ include fullurl }}"
Same response

2023-01-13 09:25 UTC, AverageMarcus commented on helm/cluster-aws/files/etc/containerd/conf.d/registry-config.toml
> +        {{ include fullurl . | quote }}
```suggestion
        {{ include "fullurl" . | quote }}
```

2023-01-17 09:10 UTC, MarcelMue commented on helm/cluster-aws/values.schema.json
> +        "harborRegistry": {
This should be moved under `registry`

2023-02-01 11:26 UTC, erkanerol commented on helm/cluster-aws/files/etc/containerd/conf.d/registry-config.toml
> +        "https://{{$value.endpoint}}",
Are you sure that the last comma is OK here?

2023-02-01 11:27 UTC, erkanerol commented on CHANGELOG.md
> +- Add `registry.harborRegistry.url`,  `registry.harborRegistry.password` and `registry.harborRegistry.username` to accomodate harbor regsitry configuration
Is this line up-to-date?

2023-02-01 11:30 UTC, erkanerol commented
@MarcelMue As far as I see, this is the same change as we have done for CAPVD. There are a few differences in configuration but it is OK.  Note that there is no harbor specific change in this PR. Harbor config will be in the configuration layer by using this new configuration interface.

2023-02-01 14:32 UTC, AndiDog commented on helm/cluster-aws/files/etc/containerd/conf.d/registry-config.toml
> +        "https://{{$value.endpoint}}",
Since it's TOML, that is fine

2023-02-01 16:11 UTC, DeeAjayi commented on helm/cluster-aws/files/etc/containerd/conf.d/registry-config.toml
> +        "https://{{$value.endpoint}}",
Yes, I have tested with a private containerd config and it won't be a problem

2023-02-02 11:44 UTC, AndiDog commented on helm/cluster-aws/files/etc/containerd/conf.d/registry-config.toml
> -      endpoint = ["https://registry-1.docker.io", "giantswarm.azurecr.io"]
This mirror config for `docker.io` gets removed by this PR, right? Shouldn't we keep it, e.g. by providing a default value? Or is that no longer necessary?

2023-02-02 12:09 UTC, DeeAjayi commented on helm/cluster-aws/files/etc/containerd/conf.d/registry-config.toml
> -      endpoint = ["https://registry-1.docker.io", "giantswarm.azurecr.io"]
It all depends on where we want to put the default values, right now it will have to be configured in the values.yml file

2023-02-03 09:32 UTC, erkanerol commented on helm/cluster-aws/files/etc/containerd/conf.d/registry-config.toml
> -      endpoint = ["https://registry-1.docker.io", "giantswarm.azurecr.io"]
For cloud-director, we don't have any default values in the chart. We configure it with app platform by default for all clusters. 

In terms of inter-provider compatibility, it is OK to set sane defaults for your provider as long as you have the same configuration interface (means values schema).

p.s. We are trying to keep apps/charts giantswarm-agnostic as much as possible. It is not feasible for each case and it is sometimes so costly. Regarding this case specifically, I wouldn't put GS registry here by default but it is up to you.

2023-02-06 08:40 UTC, AndiDog approved these changes

2023-02-06 10:31 UTC, fiunchinho commented on helm/cluster-aws/files/etc/containerd/conf.d/registry-config.toml
> -      endpoint = ["https://registry-1.docker.io", "giantswarm.azurecr.io"]
I think it makes sense keeping the config out of the chart and using our `config` system for that.

2023-02-08 14:53 UTC, MarcelMue commented
@giantswarm/team-hydra Are you ok for us to merge this? It has been tested on grizzly.

2023-02-13 13:28 UTC, fiunchinho approved these changes

2023-02-13 13:52 UTC, MarcelMue commented
/test create
/test upgrade

2023-02-13 14:12 UTC, merged