Update: use object for machine pools instead of array
giantswarm/cluster-aws pull request #209
Opened 2023-01-25 14:33 UTC by zewolfe

### What this PR does / why we need it

Towards - https://github.com/giantswarm/roadmap/issues/1614

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test create
/test upgrade

2023-01-25 14:33 UTC, zewolfe commented
/test all

2023-01-25 14:34 UTC, zewolfe commented
/test create

2023-01-26 10:11 UTC, marians commented on helm/cluster-aws/values.schema.json
> +        defaultMachinePools: {
```suggestion
        "defaultMachinePools": {
```

2023-01-26 10:30 UTC, marians commented on helm/cluster-aws/values.schema.json
>          },
I think that `machinePools` should have `patternProperties` defined, as we want to restrict the format of node pools identifiers. See https://json-schema.org/understanding-json-schema/reference/object.html#pattern-properties

The pattern should be something like `^[a-z0-9]{5,10}$`.

2023-01-26 10:48 UTC, marians commented on helm/cluster-aws/values.schema.json
>          },
... and `patternProperties` is needed in order to specify the properties that any child object here can have. This is a necessity for proper validation.

2023-01-26 11:25 UTC, zewolfe commented on helm/cluster-aws/values.schema.json
>          },
Thanks  👊🏾

2023-01-26 11:31 UTC, zewolfe commented on helm/cluster-aws/values.schema.json
> +        defaultMachinePools: {
I had updated this in a previous commit. I'm guessing maybe a refresh was needed 😃

2023-01-26 11:48 UTC, fiunchinho approved these changes
LGTM if tests pass

2023-01-26 11:50 UTC, zewolfe commented
/retest

2023-01-26 11:51 UTC, fiunchinho commented
I'm not sure if `/retest` actually works

/test create
/test upgrade

2023-01-26 12:02 UTC, zewolfe commented
I'm curious.. would the tests pass if `kubectl-gs` hasn't been updated to template the new changes?

2023-01-26 12:09 UTC, fiunchinho commented
> I'm curious.. would the tests pass if `kubectl-gs` hasn't been updated to template the new changes?

Good catch! They won't. You have to update it here https://github.com/giantswarm/test-infra/blob/master/tekton/tasks/create-cluster-capi-pure.yaml#L44

2023-01-26 12:45 UTC, zewolfe commented
Thanks! Can I make the change to the task and have the pipeline run that specific version of the task? I feel like making the change to the task now and releasing it would break other test runs in the meantime (whilst this and other PRs are waiting to be merged).

2023-01-26 14:21 UTC, fiunchinho commented
> Thanks! Can I make the change to the task and have the pipeline run that specific version of the task? I feel like making the change to the task now and releasing it would break other test runs in the meantime (whilst this and other PRs are waiting to be merged).

I'm afraid that's not possible :cry:

2023-01-26 16:20 UTC, AndiDog requested changes

2023-01-26 16:20 UTC, AndiDog commented on helm/cluster-aws/values.schema.json
> +                        "name": {
`name` is already the object key. We should forbid that key (see https://stackoverflow.com/a/30725034 for a solution) as it won't be used anymore.

2023-01-26 16:20 UTC, AndiDog commented on helm/cluster-aws/values.schema.json
> +            "type": "object"
We should have the same schema here. What about defining it once, and then referencing the schema for both `defaultMachinePools` and `machinePools`. JSON schema has a [`$defs` example](http://json-schema.org/understanding-json-schema/structuring.html#defs).

2023-01-27 14:38 UTC, zewolfe commented on helm/cluster-aws/values.schema.json
> +            "type": "object"
Good shout

2023-01-30 12:04 UTC, fiunchinho commented on CHANGELOG.md
> +- Use object for `.machinePools` schema instead of array. This is to make it easier to overwrite values when using GitOps.
I was thinking that it may be a good idea to make this breaking change more prominent in the changelog, similar to https://github.com/giantswarm/cluster-aws/blob/master/CHANGELOG.md#breaking-change

2023-02-02 11:04 UTC, AndiDog approved these changes

2023-02-02 13:15 UTC, merged