Add migration help to changelog
giantswarm/cluster-aws pull request #267
Opened 2023-03-24 16:36 UTC by marians

### What this PR does / why we need it

This PR adds help to migrate values from v0.27.0 to v0.28.0.

2023-03-27 07:07 UTC, AverageMarcus commented on CHANGELOG.md
> +**Note**: this release includes values schema changes which break compatibility with previous versions.
It might be better to include this in the project README.md and link to it from here. There's a couple examples of this already e.g. https://github.com/giantswarm/cluster-aws/blob/migration-help/CHANGELOG.md#breaking-change-1

2023-03-27 07:45 UTC, marians commented on CHANGELOG.md
> +**Note**: this release includes values schema changes which break compatibility with previous versions.
Honestly I think the changelog is the better place for such migration info. Especially once we have values documentation in the README, which will make the README quite long. I'm sure only few people will expect this down there. So I'd rather vote for moving all migration info to the changelog, which could be done in a separate PR.

2023-03-27 09:11 UTC, AndiDog reviewed
LGTM so far

2023-03-27 09:11 UTC, AndiDog commented on CHANGELOG.md
> +**Note**: this release includes values schema changes which break compatibility with previous versions.
I agree that a strong hint about a breaking change in the _changelog_ is where people would look at, including our own developers.

For large-scale changes like these, we have to ensure that people cannot accidentally use the old values. Since we now have `required "connectivity.dns.mode required" .Values.connectivity.dns.mode`, an old values.yaml becomes broken and leads to a loud error as it should be, instead of creating a cluster with wrong values 👍.

Can we replace `## Changed` with `## Breaking changes` as well?

2023-03-27 09:23 UTC, AndiDog requested changes
Found one problem with the migration script – unset values are explicitly set to `null`. In my case, I got this as output:

```yaml
controlPlane:
  replicas: 3
  apiMode: private
  oidc: null
connectivity:
  availabilityZoneUsageLimit: 3
  bastion: {}
  dns:
    additionalVpc: null
    mode: private
    resolverRulesOwnerAccount: null
  network:
    podCidr: null
    serviceCidr: null
    vpcCidr: 10.226.0.0/18
  proxy:
    httpProxy: http://[...]
    httpsProxy: http://[...]
    noProxy: null
  sshSsoPublicKey: null
  subnets:
    - cidrBlocks:
        - availabilityZone: a
          cidr: 10.226.0.0/20
        - availabilityZone: b
          cidr: 10.226.16.0/20
        - availabilityZone: c
          cidr: 10.226.32.0/20
      isPublic: false
  topology:
    mode: GiantSwarmManaged
    prefixListId: null
    transitGatewayId: null
  vpcEndpointMode: null
  vpcMode: private
internal:
  hashSalt: null
  kubernetesVersion: null
metadata:
  description: Andreas Sommer's test cluster
  name: andreas42
  organization: giantswarm
nodePools:
  machine-pool0:
    instanceType: m5.xlarge
    maxSize: 10
    minSize: 3
    rootVolumeSizeGB: 300
providerSpecific:
  ami: null
  awsClusterRoleIdentityName: null
  flatcarAwsAccount: null
  region: null
```

2023-03-27 09:46 UTC, marians commented on CHANGELOG.md
> +Also be aware that if you were using `.aws.awsClusterRole` to specify a role in v0.27.0, this cannot be migrated automatically. Instead you have to make sure to have a [AWSClusterRoleIdentity](https:
This change was not only about the property name. The meaning of the property has also changed. With `.aws.awsClusterRole` the name of the role had to be set, while `.providerSpecific.awsClusterRoleIdentityName` is the name of a kubernetes resource. By adding "the deprecated name" this would become less clear, I think.

2023-03-28 09:58 UTC, marians commented on CHANGELOG.md
> +**Note**: this release includes values schema changes which break compatibility with previous versions.
Not all values schema changes were actually breaking. With the note above, is it clear enough that there are incompatible changes?

2023-03-28 12:15 UTC, calvix approved these changes
looks good

2023-03-28 13:41 UTC, AndiDog commented
> Approval if `additionalVpc` is on purpose 🤷

Not sure how to handle this: our code uses singular by mistake despite it being a comma-separated list in our implementation (annotation `const AWSDNSAdditionalVPC = "aws.giantswarm.io/dns-assign-additional-vpc"`, dns-operator-aws allows multiple comma-separated values in there).

2023-03-29 07:39 UTC, marians commented on CHANGELOG.md
> +  with(select(.network.dnsAssignAdditionalVPCs != null);    .connectivity.dns.additionalVpc = (.network.dnsAssignAdditionalVPCs | split(","))) |
This is the actual name of the property. Since `VPC` is an acronym, it's not necessary to add an `s` for a plural form.

2023-03-29 07:39 UTC, merged