Move podCidr and serviceCidr to new properties
giantswarm/cluster-aws pull request #301
Opened 2023-05-03 11:59 UTC by fiunchinho

### What this PR does / why we need it
Towards https://github.com/giantswarm/giantswarm/issues/26798

### Checklist

- [X] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test create
/test upgrade
/run cluster-test-suites

2023-05-03 13:57 UTC, fiunchinho commented
/test create
/test upgrade
/run cluster-test-suites

2023-05-04 11:55 UTC, marians commented on helm/cluster-aws/values.schema.json
> +                    "title": "ClusterNetwork",
Titles should always be sentence case.

```suggestion
                    "title": "Cluster network",
```

2023-05-04 11:58 UTC, marians requested changes
Having two network sections on the same level will be extremely confusing. Let's please fix that!

![image](https://user-images.githubusercontent.com/273727/236197024-517a30e7-f67c-42aa-9d21-005894e5e6b8.png)

2023-05-09 08:16 UTC, fiunchinho commented
This PR is blocked until we reach agreement here https://github.com/giantswarm/giantswarm/issues/26451

2023-05-10 10:26 UTC, fiunchinho commented
/test upgrade
/run cluster-test-suites

2023-05-10 10:38 UTC, nprokopic commented on helm/cluster-aws/values.yaml
> -    serviceCidr: 172.31.0.0/16
Not sure how important (depending on the number of existing clusters out there and who and when will be upgrading them), maybe not important at all, removing these could break the existing clusters if they do not immediately set the new values when upgrading the version of `cluster-aws`.

Something like this could be smoother and more friendly to backward compatibility (if that's even needed):
- Change 1:
  - Add new values fields
  - In templates use new fields and fallback to old fields if new ones are not specified
  - Deprecate old values fields
- Leave both old and new fields for few releases
- Change 2:
  - Remove old values fields
  - Use just the new fields

2023-05-10 10:42 UTC, fiunchinho commented on helm/cluster-aws/values.yaml
> -    serviceCidr: 172.31.0.0/16
We can apply the changes at the same time when creating the PR on `management-clusters-fleet`. That's how we've done it in the past. I think that's fine while we manage the clusters. Once we don't manage them and the customers start managing them, then we need to add backwards compatible changes. But for now I think it's fine. Does that make sense?

2023-05-10 11:04 UTC, fiunchinho commented
/test upgrade
/run cluster-test-suites

2023-05-10 12:09 UTC, nprokopic commented on helm/cluster-aws/values.yaml
> -    serviceCidr: 172.31.0.0/16
Yup, makes sense :)

2023-05-10 13:22 UTC, marians commented
FYI: the current way looks good to me :)

![image](https://github.com/giantswarm/cluster-aws/assets/273727/aff27fb1-b15f-4f92-a0a4-d5944a5866c9)

2023-05-10 13:22 UTC, marians commented
FYI: the current way looks good to me :)

![image](https://github.com/giantswarm/cluster-aws/assets/273727/aff27fb1-b15f-4f92-a0a4-d5944a5866c9)

2023-05-11 07:55 UTC, fiunchinho commented
hey @nprokopic @marians any reasons not to approve the PR? is there anything missing?

2023-05-11 08:03 UTC, nprokopic approved these changes

2023-05-11 08:03 UTC, nprokopic commented
> hey @nprokopic @marians any reasons not to approve the PR? is there anything missing?

Forgot to click the button yesterday :grimacing:

2023-05-11 13:59 UTC, marians approved these changes
The change looks like an improvement to me.

Since this change is breaking schema compatibility, I recommend to provide a script/command like we did in v0.28.0 (see CHANGELOG.md).

2023-05-11 14:06 UTC, fiunchinho commented
> The change looks like an improvement to me.
> 
> Since this change is breaking schema compatibility, I recommend to provide a script/command like we did in v0.28.0 (see CHANGELOG.md).

I think that's a good idea generally. But in this case I don't think it's necessary https://github.com/giantswarm/cluster-aws/pull/301#discussion_r1189719020

2023-05-11 15:22 UTC, AndiDog commented on helm/cluster-aws/values.schema.json
> +                            "required": [
[repeated]

Is it `required` if it has a `default`? (see [R9 in the schema RFC](https://github.com/giantswarm/rfc/pull/55/files))

2023-05-11 16:01 UTC, fiunchinho commented on helm/cluster-aws/templates/_control_plane.tpl
> +        serviceSubnet: {{ join "," .Values.connectivity.network.services.cidrBlocks }}
[According to the docs](https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api/bootstrap.cluster.x-k8s.io/KubeadmConfig/v1beta1@v1.4.1#spec-clusterConfiguration-networking-serviceSubnet) it accepts a comma-delimited string.

2023-05-11 16:02 UTC, fiunchinho commented on helm/cluster-aws/values.schema.json
> +                            "required": [
Fixed

2023-05-11 16:21 UTC, fiunchinho commented on helm/cluster-aws/templates/_cluster.tpl
> +      cidrBlocks: {{ .Values.connectivity.network.services.cidrBlocks }}
Fixed.

2023-05-11 19:35 UTC, kopiczko approved these changes

2023-05-12 07:32 UTC, marians commented
@fiunchinho I think the repo README.md includes some examples that should be adapted to this schema change.

2023-05-15 15:29 UTC, AndiDog approved these changes

2023-05-15 15:59 UTC, fiunchinho commented
> @fiunchinho I think the repo README.md includes some examples that should be adapted to this schema change.

I don't think we mention the changed fields in the examples.

2023-05-15 16:04 UTC, fiunchinho commented
/test upgrade
/run cluster-test-suites

2023-05-16 07:25 UTC, fiunchinho commented
/run cluster-test-suites

2023-05-16 08:01 UTC, merged