Add value to configure control plane load balancer allow list
giantswarm/cluster-aws pull request #343
Opened 2023-07-13 11:05 UTC by fiunchinho

### What this PR does / why we need it
Towards https://github.com/giantswarm/roadmap/issues/2351

### Checklist

- [X] Update changelog in CHANGELOG.md.

2023-07-18 09:16 UTC, marians commented on helm/cluster-aws/values.schema.json
> +                    "title": "Load Balancer Allow list",
```suggestion
                    "title": "Load balancer allow list",
```

2023-09-28 08:29 UTC, marians commented on helm/cluster-aws/values.schema.json
> +                    "description": "IPs that are allowed to connect to the control plane load balancer.",
Aligning this with other CIDR properties and their descriptions:

```suggestion
                    "description": "IPv4 address ranges that are allowed to connect to the control plane load balancer, in CIDR notation.",
```

2023-09-28 08:29 UTC, marians commented on helm/cluster-aws/values.schema.json
> +                        "title": "CIDR"
```suggestion
                        "title": "Address range"
```

2023-09-28 10:04 UTC, fiunchinho commented
/run cluster-test-suites

2023-09-28 12:55 UTC, marians commented
I think schemadocs needs updating, too

2023-09-28 13:42 UTC, fiunchinho commented
The e2e tests on this PR will fail until CAPA `v2.2.3` release is deployed on `grizzly`.

2023-09-28 15:15 UTC, marians commented on helm/cluster-aws/values.schema.json
> +                    "description": "IPv4 address ranges that are allowed to connect to the control plane load balancer, in CIDR notation. When setting this field, remember to add the Management clust
Brand police here 🚨 

```suggestion
                    "description": "IPv4 address ranges that are allowed to connect to the control plane load balancer, in CIDR notation. When setting this field, remember to add the Management cluster Nat Gateway IPs provided by Giant Swarm so that the cluster can still be managed.",
```

2023-09-28 15:16 UTC, marians commented on helm/cluster-aws/README.md
> +| `controlPlane.allowList` | **Load balancer allow list** - IPv4 address ranges that are allowed to connect to the control plane load balancer, in CIDR notation. When setting this field, remember to
```suggestion
| `controlPlane.allowList` | **Load balancer allow list** - IPv4 address ranges that are allowed to connect to the control plane load balancer, in CIDR notation. When setting this field, remember to add the Management cluster Nat Gateway IPs provided by Giant Swarm so that the cluster can still be managed.|**Type:** `array`<br/>**Default:** `["0.0.0.0/0"]`|
```

2023-10-06 11:46 UTC, AndiDog requested changes

2023-10-06 11:46 UTC, AndiDog commented on helm/cluster-aws/templates/_aws_cluster.tpl
> +      {{- toYaml .Values.controlPlane.allowList | nindent 6 }}
Indentation needs to match the existing list item for the Kubernetes API, so shouldn't it be `nindent 4`?

2023-10-06 11:46 UTC, AndiDog commented on CHANGELOG.md
> +- Add `controlPlane.allowList` to configure control plane load balancer ingress rules.
The name is quite unclear. What about `controlPlane.loadBalancerIngressRules` which matches CAPA naming? Also, it looks like the default value `["0.0.0.0/0"]` shouldn't work because `[]IngressRule` is expected, not `[]string`.

The description shouldn't say anything about IPv4. The `IngressRule` type supports IPv6 as well.

Also, should we move this into `.Values.providerSpecific`?

2023-10-09 16:00 UTC, fiunchinho commented on helm/cluster-aws/templates/_aws_cluster.tpl
> +      {{- toYaml .Values.controlPlane.allowList | nindent 6 }}
If I use `nindent 4` it would look like this, and it wouldn't work

```
- description: "Kubernetes API"
      protocol: tcp
      fromPort: 6443
      toPort: 6443
      cidrBlocks:
    - 1.2.3.4/32
```

2023-10-10 14:28 UTC, fiunchinho commented on CHANGELOG.md
> +- Add `controlPlane.allowList` to configure control plane load balancer ingress rules.
Regarding `IPv4`, we are currently only setting `cidrBlocks` field, which is IPv4. I don't know if we support clusters using IPv6 at this point.

2023-10-10 15:04 UTC, fiunchinho commented
/run cluster-test-suites

2023-10-10 15:19 UTC, AndiDog commented on CHANGELOG.md
> +- Add `controlPlane.allowList` to configure control plane load balancer ingress rules.
I was confused by

```
cidrBlocks:
  {{- toYaml .Values.controlPlane.loadBalancerIngressRules | ... }}
```

because the name `controlPlane.loadBalancerIngressRules` reads as if users can pass additional rules. Therefore I commented as if that was the goal.

However, what you currently implement is rather something like `controlPlane.loadBalancerIngressAllowCidrBlocks`, right? I'm fine to only allow configuring IPv4 blocks, defaulting to `0.0.0.0/0`, but then we need to give the value a good name. We can still migrate to supporting the configuration of full rules _later_.

2023-10-10 16:19 UTC, AndiDog commented on helm/cluster-aws/README.md
> +| `controlPlane.loadBalancerIngressAllowCidrBlocks` | **Load balancer allow list** - IPv4 address ranges that are allowed to connect to the control plane load balancer, in CIDR notation. When setting
At best, customers shouldn't need to take care of adding MC gateway IPs. Can we `{{ lookup [...] "AWSCluster" .Values.managementCluster }}` (pseudocode) the MC and check its `AWSCluster.status.networkStatus.natGatewaysIPs`?

2023-10-10 16:19 UTC, AndiDog commented on helm/cluster-aws/values.schema.json
> +                    "default": [
We could also default to leaving this off, as before

2023-10-11 09:03 UTC, fiunchinho commented on helm/cluster-aws/README.md
> +| `controlPlane.loadBalancerIngressAllowCidrBlocks` | **Load balancer allow list** - IPv4 address ranges that are allowed to connect to the control plane load balancer, in CIDR notation. When setting
We discussed on Slack to avoid using `lookup` and just document how to get the IPs.

2023-10-11 09:03 UTC, fiunchinho commented on helm/cluster-aws/values.schema.json
> +                    "default": [
Removed

2023-10-11 09:06 UTC, whites11 approved these changes

2023-10-11 09:13 UTC, calvix commented on helm/cluster-aws/values.schema.json
> +                "loadBalancerIngressAllowCidrBlocks": {
I personally do not like that adding MC nat gateways is a manual step

2023-10-11 09:13 UTC, calvix commented on helm/cluster-aws/values.schema.json
> +                "loadBalancerIngressAllowCidrBlocks": {
this will be often forgotten by customer and we will get lot of pages because of it

2023-10-11 15:03 UTC, fiunchinho commented on helm/cluster-aws/values.schema.json
> +                "loadBalancerIngressAllowCidrBlocks": {
We could automate it in `kubectl-gs template cluster`

2023-10-11 17:10 UTC, AndiDog commented on helm/cluster-aws/templates/_aws_cluster.tpl
> +      - 95.179.153.65/32
There must be a comment for these, and at best a link to where those come from

2023-10-12 08:40 UTC, calvix approved these changes

2023-10-12 08:42 UTC, AndiDog approved these changes

2023-10-12 08:45 UTC, merged