remove-support-for-dns-mode-private
giantswarm/cluster-aws pull request #380
Opened 2023-09-20 14:37 UTC by calvix

### What this PR does / why we need it

### Checklist

- [ ] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

2023-09-20 15:02 UTC, calvix commented
/run cluster-test-suites

2023-09-20 15:05 UTC, fiunchinho requested changes
I think we can remove this now https://github.com/giantswarm/cluster-aws/blob/master/helm/cluster-aws/templates/_aws_cluster.tpl#L12-L16

And also the `additionalVpc` field from the schema and values files.

2023-09-20 15:50 UTC, calvix commented
> I think we can remove this now [`master`/helm/cluster-aws/templates/_aws_cluster.tpl#L12-L16](https://github.com/giantswarm/cluster-aws/blob/master/helm/cluster-aws/templates/_aws_cluster.tpl?rgh-link-date=2023-09-20T15%3A05%3A13Z#L12-L16)
> 
> And also the `additionalVpc` field from the schema and values files.

removed

2023-09-21 06:19 UTC, AndiDog requested changes

2023-09-21 06:19 UTC, AndiDog commented on helm/cluster-aws/values.schema.json
> -                        "additionalVpc": {
You need to run

```
make normalize-schema generate-values generate-docs validate-schema
```

2023-09-21 07:16 UTC, calvix commented on helm/cluster-aws/values.schema.json
> -                        "additionalVpc": {
I always run that, otherwise the  `JSON schema validation` CI would fail

2023-09-21 07:17 UTC, calvix commented
/run cluster-test-suites

2023-09-21 08:06 UTC, fiunchinho reviewed
Actually, would it make sense to remove the whole `dns` block? I don't think we need it anymore, right? https://github.com/giantswarm/cluster-aws/blob/master/helm/cluster-aws/values.schema.json#L224-L265

2023-09-21 08:09 UTC, calvix commented
> Actually, would it make sense to remove the whole `dns` block? I don't think we need it anymore, right? [`master`/helm/cluster-aws/values.schema.json#L224-L265](https://github.com/giantswarm/cluster-aws/blob/master/helm/cluster-aws/values.schema.json?rgh-link-date=2023-09-21T08%3A06%3A23Z#L224-L265)

Don't we still use the resolver rules in the product?

2023-09-21 08:11 UTC, calvix commented on helm/cluster-aws/values.schema.json
> -                        "additionalVpc": {
Oh i was missing `generate-docs` I wonder why that command is missing from the list in the Readme, just added it

2023-09-21 08:11 UTC, calvix commented on helm/cluster-aws/values.schema.json
> -                        "additionalVpc": {
sorry my bad

2023-09-21 08:11 UTC, fiunchinho commented
> > Actually, would it make sense to remove the whole `dns` block? I don't think we need it anymore, right? [`master`/helm/cluster-aws/values.schema.json#L224-L265](https://github.com/giantswarm/cluster-aws/blob/master/helm/cluster-aws/values.schema.json?rgh-link-date=2023-09-21T08%3A06%3A23Z#L224-L265)
> 
> Don't we still use the resolver rules in the product?

I think we only needed it when using private DNS, but if we are dropping support for private dns, I don't think we need it anymore. I may be wrong though.

2023-09-21 08:15 UTC, calvix commented
@T-Kukawka DO we wanna keep a feature called Resolver rules in our product or do we wanna get rid of it too? 
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver.html

2023-09-21 08:28 UTC, AndiDog approved these changes

2023-09-21 08:51 UTC, T-Kukawka commented
Personally i would leave this feature if it does not bring much of overhead on our side, especially for the future to target more 'hybrid' customers where this can come in handy.

2023-09-21 09:08 UTC, fiunchinho approved these changes

2023-09-21 09:09 UTC, calvix commented
/run cluster-test-suites

2023-09-21 10:07 UTC, merged