Expose Helm values for HelmReleases
giantswarm/cluster-aws pull request #432
Opened 2023-11-22 00:08 UTC by nprokopic

### What this PR does / why we need it

Towards https://github.com/giantswarm/roadmap/issues/2940

### Checklist

- [ ] Update changelog in CHANGELOG.md.

### Trigger e2e tests

<!--
We currently have one pipeline that tests both cluster creation and cluster upgrades. You can trigger this pipeline by writing this commands in a pull request comment or description
- `/run cluster-test-suites`

2023-11-23 21:59 UTC, nprokopic commented on helm/cluster-aws/values.schema.json
> +                                    "description": "Linter is failing without at least one property."
I'll fix the linter so we don't have to add these dummy values to public customer-facing Helm values.

2023-11-23 22:00 UTC, nprokopic commented
Will fix this before merging https://github.com/giantswarm/cluster-aws/pull/432#discussion_r1403758755

2023-11-24 15:09 UTC, nprokopic commented on helm/cluster-aws/values.schema.json
> +                                    "description": "Linter is failing without at least one property."
Done, linter now does not enforce that `global.apps.*` have defined properties in the schema.

2023-11-28 16:05 UTC, AndiDog requested changes

2023-11-28 16:05 UTC, AndiDog commented on helm/cluster-aws/templates/aws-ebs-csi-driver-helmrelease.yaml
> +  {{- $customAwsEbsCsiDriverHelmValues := ($.Values.global.apps).awsEbsCsiDriver -}}
```suggestion
  {{- $customAwsEbsCsiDriverHelmValues := $.Values.global.apps.awsEbsCsiDriver -}}
```

Parentheses not needed?!

[repeated]

2023-11-28 16:05 UTC, AndiDog commented on helm/cluster-aws/templates/aws-ebs-csi-driver-helmrelease.yaml
> +  values: {{ $awsEbsCsiDriverHelmValues | toYaml | nindent 4 }}
```suggestion
  values: {{- $awsEbsCsiDriverHelmValues | toYaml | nindent 4 }}
```

to avoid trailing whitespace

[repeated]

2023-11-30 11:58 UTC, nprokopic commented on helm/cluster-aws/templates/aws-ebs-csi-driver-helmrelease.yaml
> +  {{- $customAwsEbsCsiDriverHelmValues := ($.Values.global.apps).awsEbsCsiDriver -}}
Fixed.

2023-12-01 13:02 UTC, nprokopic commented
/run cluster-test-suites

2023-12-01 13:55 UTC, paurosello approved these changes
Looks good to me!

2023-12-01 14:40 UTC, nprokopic commented
> ## cluster-test-suites
> Run name	`pr-cluster-aws-432-cluster-test-suitespjmsc`
> Commit SHA	[0a5a30c](https://github.com/giantswarm/cluster-aws/commit/0a5a30c36e49345ae12754a7522e70b9e602672f)
> Result	Failed ❌
> [📋 View full results in Tekton Dashboard](https://tekton.ci.giantswarm.io/#/namespaces/tekton-pipelines/pipelineruns/pr-cluster-aws-432-cluster-test-suitespjmsc?pipelineTask=display-results&step=display-results)
> 
> **Rerun trigger:** `/run cluster-test-suites`

E2E test failures are due to issue unrelated to the change in this PR. The failures are happening in default-apps-aws and those have not been affected by neither this nor previous PRs I had in cluster-aws. There are also some known issue with cert-manager and prometheus-operator and E2E test being flaky because of those.

Therefore merging this.

2023-12-01 15:46 UTC, AndiDog approved these changes

2023-12-01 21:24 UTC, nprokopic commented
/run cluster-test-suites

2023-12-02 00:15 UTC, merged