Add support for Release CRs
giantswarm/cluster-aws pull request #637
Opened 2024-06-04 14:09 UTC by nprokopic

### What this PR does / why we need it

This PR adds support for using Release CRs and getting k8s, OS and app version, catalog and dependencies from there.

Will add more details here, for now see https://github.com/giantswarm/rfc/pull/96 for more.

### Checklist

- [ ] Updated CHANGELOG.md.

2024-06-04 14:10 UTC, nprokopic commented on helm/cluster-aws/values.schema.json
> +                    "osImage": {
I will actually remove this, as variant will be also in the Release CR.

2024-06-06 13:12 UTC, nprokopic commented
Will rebase and update PR.

2024-06-06 13:16 UTC, mnitchev approved these changes

2024-06-06 13:22 UTC, AndiDog reviewed
Mostly ready to go, just minor stuff

2024-06-06 13:22 UTC, AndiDog commented on helm/cluster-aws/templates/_helpers.tpl
> +{{- if and $suffix (ne $suffix "N/A") }}
Can we please add `{{/* comments */}}` to explain what's going on here?

2024-06-06 13:22 UTC, AndiDog commented on helm/cluster-aws/templates/aws-ebs-csi-driver-helmrelease.yaml
> +      {{- $appVersion := include "cluster.app.version" $ }}
Also possible: `mustMergeOverwrite (mustDeepCopy $) (dict "appName" "myapp")` (not tested)

2024-06-06 16:50 UTC, nprokopic commented on helm/cluster-aws/templates/aws-ebs-csi-driver-helmrelease.yaml
> +      {{- $appVersion := include "cluster.app.version" $ }}
You mean to pass in a new dict (deep copy of `$` + needed value) so we don't modify `$`?

2024-06-12 16:11 UTC, nprokopic commented
let's see if this works 🙈 


/run cluster-test-suites

2024-06-12 16:19 UTC, nprokopic commented
From the [e2e tests](https://tekton.ci.giantswarm.io/#/namespaces/tekton-pipelines/pipelineruns/pr-cluster-aws-637-cluster-test-suitesvvlfz?pipelineTask=run-tests&taskRunName=pr-cluster-aws-637-cluster-test-suitesvvlfz-run-tests-2&step=run-tests) ATM 🥹 ❤️ 

```
  {"level":"info","ts":"2024-06-12T16:13:37Z","msg":"Cluster App is supported by Releases"}
  {"level":"info","ts":"2024-06-12T16:13:38Z","msg":"Release name: 'aws-25.0.1-t.86x803cgg3'"}
```

@AverageMarcus did a wonderful job!

2024-06-13 07:22 UTC, nprokopic commented
/run cluster-test-suites TARGET_SUITES=./providers/capa/upgrade

2024-06-13 08:52 UTC, nprokopic commented
Re-running tests with the new [v25.0.0-alpha.2](https://github.com/giantswarm/releases/releases/tag/aws%2Fv25.0.0-alpha.2) release (tests picks up the latest one)

/run cluster-test-suites

2024-06-13 13:20 UTC, nprokopic commented
Re-running tests with the new [v25.0.0-alpha.3](https://github.com/giantswarm/releases/releases/tag/aws%2Fv25.0.0-alpha.3) release

/run cluster-test-suites

2024-06-13 14:23 UTC, nprokopic commented
Upgrade fails with

```
  {"level":"info","ts":"2024-06-13T14:09:14Z","msg":"deployment kube-system/cert-exporter-deployment has 0/1 replicas available"}
  {"level":"info","ts":"2024-06-13T14:09:25Z","msg":"deployment kube-system/cert-exporter-deployment has 0/1 replicas available"}
  {"level":"info","ts":"2024-06-13T14:09:36Z","msg":"deployment kube-system/cert-exporter-deployment has 0/1 replicas available"}
  [FAILED] in [It] - /app/internal/common/basic.go:80 @ 06/13/24 14:09:39.345
• [FAILED] [900.001 seconds]
Basic upgrade test basic [It] has all its Deployments Ready (means all replicas are running)
/app/internal/common/basic.go:76

  [FAILED] Timed out after 900.001s.
  Expected success, but got an error:
      <*errors.errorString | 0xc000abd1f0>: 
      deployment kube-system/cert-exporter-deployment has 0/1 replicas available
      {
          s: "deployment kube-system/cert-exporter-deployment has 0/1 replicas available",
      }
  In [It] at: /app/internal/common/basic.go:80
```

2024-06-13 14:23 UTC, nprokopic commented
/run cluster-test-suites TARGET_SUITES=./providers/capa/upgrade

2024-06-14 09:29 UTC, nprokopic commented
debugging failures


/run cluster-test-suites TARGET_SUITES=./providers/capa/upgrade

2024-06-17 08:09 UTC, T-Kukawka commented
what is the status here @nprokopic ?

2024-06-19 09:51 UTC, nprokopic commented
/run cluster-test-suites

2024-06-19 12:57 UTC, paurosello commented
/run cluster-test-suites

2024-06-20 13:01 UTC, nprokopic commented on helm/cluster-aws/templates/_helpers.tpl
> +{{- if and $suffix (ne $suffix "N/A") }}
Added comments.

2024-06-20 13:35 UTC, fiunchinho requested changes
I don't think this is the right approach. I wrote some of my thoughts here https://github.com/giantswarm/rfc/pull/96#issuecomment-2178934882

2024-06-20 14:56 UTC, nprokopic commented
Upgrade test expectedly failed with (issue with launch template updates):

```
Basic upgrade test basic [It] has all the worker nodes running
/app/internal/common/basic.go:63

  [FAILED] Timed out after 900.000s.
  Expected success, but got an error:
      <*errors.errorString | 0xc000d21850>: 
      unexpected number of nodes
      {
          s: "unexpected number of nodes",
      }
  In [It] at: /app/internal/common/basic.go:74 @ 06/20/24 13:51:52.738
```

CAPA Cilium ENI mode suite failed with:

```
  {"level":"info","ts":"2024-06-20T13:29:09Z","msg":"App status for 't-jp54o5zwvzjgt8io3c-kyverno-policy-operator' is not yet as expected: expectedStatus='deployed' actualStatus='pending-install' (reason: 'Initial install underway')"}

```

This has been happening randomly lately with apps from the security bundle 😞

2024-06-20 15:04 UTC, fiunchinho commented on helm/cluster-aws/templates/_helpers.tpl
> +release.giantswarm.io/version: {{ .Values.global.release.version | trimPrefix "v" | quote }}
This common labels will get applied to the `cluster-aws` CAPI manifests. I don't think we need the release label in those manifests, as they are baked in the `cluster-aws` release. So I'd remove the label.

2024-06-20 16:11 UTC, nprokopic commented on helm/cluster-aws/templates/_helpers.tpl
> +release.giantswarm.io/version: {{ .Values.global.release.version | trimPrefix "v" | quote }}
> This common labels will get applied to the cluster-aws CAPI manifests.

That was the intention, so it's easier to see from which release some resources are, as multiple releases can have the same cluster-aws version. e.g. you can easily get AWSCluster, AWSMachinePool, etc from all clusters for a specific release.

2024-06-20 17:22 UTC, nprokopic commented
After having a conversation in Slack we agreed to continue with this.

2024-06-20 17:23 UTC, nprokopic commented
Adding `skip/ci` label, as test failures are known and expected.

2024-06-20 17:26 UTC, merged

2024-06-24 06:39 UTC, fiunchinho commented on helm/cluster-aws/templates/_helpers.tpl
> +release.giantswarm.io/version: {{ .Values.global.release.version | trimPrefix "v" | quote }}
Oh right, I didn't think of that. It makes sense now.