Add nodetags
giantswarm/cluster-aws pull request #929
Opened 2024-11-08 13:58 UTC by paurosello

### What this PR does / why we need it

Add tags that are node specific, not for all resources

### Checklist

- [ ] Updated CHANGELOG.md.

### Trigger E2E tests

/run cluster-test-suites

2024-11-08 18:17 UTC, Gacko commented on helm/cluster-aws/templates/_machine_pools.tpl
> +    {{- if $.Values.global.providerSpecific.additionalNodeTags -}}{{- toYaml $.Values.global.providerSpecific.additionalNodeTags | nindent 4 }}{{- end}}
```suggestion
    {{- if $.Values.global.providerSpecific.additionalNodeTags }}
    {{- toYaml $.Values.global.providerSpecific.additionalNodeTags | nindent 4 }}
    {{- end}}
```

2024-11-08 18:17 UTC, Gacko commented on helm/cluster-aws/templates/_control_plane.tpl
> +  {{- if $.Values.global.providerSpecific.additionalNodeTags -}}{{- toYaml $.Values.global.providerSpecific.additionalNodeTags | nindent 2 }}{{- end}}
```suggestion
{{- if $.Values.global.providerSpecific.additionalNodeTags }}
additionalTags: {{ toYaml $.Values.global.providerSpecific.additionalNodeTags | nindent 2 }}
{{- end}}
```

2024-11-11 10:07 UTC, fiunchinho requested changes
This should be mentioned in the changelog.

2024-11-12 08:21 UTC, paurosello commented
/run cluster-test-suites

2024-11-12 08:31 UTC, fiunchinho commented on CHANGELOG.md
> +- Add `global.providerSpecific.additionalNodeTags`. Field used to specify tags applied to nodes only.
```suggestion
### Added

- Add `global.providerSpecific.additionalNodeTags`. Field used to specify tags applied to nodes only.
```

2024-11-12 09:16 UTC, fiunchinho approved these changes

2024-11-12 09:18 UTC, merged